In [1]:
import numpy as np

In [2]:
print("Hello world")

Hello world


To create an array and data type is int8

In [6]:
myarr = np.array([1,2,3,4,5],np.int8)

In [4]:
myarr

array([1, 2, 3, 4, 5])

In [7]:
myarr

array([1, 2, 3, 4, 5], dtype=int8)

To access 2nd index array

In [8]:
myarr[2]

3

making it 2 d array

In [9]:
myarr = np.array([[1,2,3,4,5]],np.int8)

In [10]:
myarr[0,1]

2

to know the size of array

In [11]:
myarr.shape

(1, 5)

to know the data type of array

In [12]:
myarr.dtype

dtype('int8')

# Array creation 1 : conversion form other python structures

In [13]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

to make dtype object, use curly brackets

In [19]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

# Array creation 2 : intrinsic numpy array craetion objects

In [21]:
zero = np.zeros((2,5))

In [22]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zero.shape

(2, 5)

In [24]:
zero.dtype

dtype('float64')

np.arange() - (single r) creates an instance of ndarray with evenly spaced values and returns the reference to it.

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

linspace - Return evenly spaced numbers over a specified interval. from 1 to 5, get 12 evenly spaced numbers

In [28]:
lspace = np.linspace(1,5,12)

In [29]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

np.empty gives empty array with random values

In [31]:
em = np.empty((4,6))

In [32]:
em

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.11261434e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.42417221e-306, 1.42419530e-306, 1.37962456e-306,
        1.11260959e-306, 9.34603679e-307, 1.11260348e-306],
       [1.33511562e-306, 1.11260348e-306, 1.33511562e-306,
        9.79094970e-307, 1.69121503e-306, 2.56765117e-312]])

empty_like() - Return a new array with the same shape and type as a given array

In [34]:
emp_like = np.empty_like(lspace)

In [35]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

np.identity() -  n x n array with its main diagonal set to one, and all other elements 0.

In [36]:
ide = np.identity(5)

In [37]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
ide.shape

(5, 5)

To use reshape function

In [39]:
arr = np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

reshaped into 3x33 matrix

In [42]:
arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

error because 3x31 = 93 but array has 99 elements so cannot reshape

To make it 1d array again, ravel() - Return a contiguous flattened array. A 1-D array

In [43]:
arr = arr.ravel()

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Introduction of Axis

In [45]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [46]:
arr = np.array(x)

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

axis = 0 gives sum of rows elements of each column

In [48]:
arr.sum(axis=0)

array([12, 15, 18])

axis = 1 gives sum of coloumns of each row

In [49]:
arr.sum(axis=1)

array([ 6, 15, 24])

To get the transpose of an array use arr.T

In [50]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

To get an iteration, use ar.flat

In [51]:
arr.flat

In [52]:
for item in arr.flat :
    print(item)

1
2
3
4
5
6
7
8
9


To get the dimension of an array

In [53]:
arr.ndim

2

In [54]:
arr.size

9

To get total bytes consumed

In [55]:
arr.nbytes

36

argmax() Returns the indices of the maximum values along an axis.

In [56]:
arr.argmax()

8

In [57]:
arr.argmin()

0

argsort() Returns the indices that would sort an array.

In [58]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

But it is a 2d array that is why gave repetiting so use axis here

In [59]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [60]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [61]:
arr2 = np.array([[3,4,0],[1,6,1],[2,2,2]])

In [62]:
arr2

array([[3, 4, 0],
       [1, 6, 1],
       [2, 2, 2]])

Adding two matrices


In [63]:
arr+arr2

array([[ 4,  6,  3],
       [ 5, 11,  7],
       [ 9, 10, 11]])

although same cannot happen with list we can extend it but not add,, for ex

In [64]:
[2,3,4]+[2,4,5]

[2, 3, 4, 2, 4, 5]

In [65]:
arr*arr2

array([[ 3,  8,  0],
       [ 4, 30,  6],
       [14, 16, 18]])

To get square root of each element

In [67]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
arr.sum()

45

In [69]:
arr.max()

9

In [70]:
arr.min()

1

To find elements with the given condition, we use where

In [71]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

To count how many non zero elements are there 

In [72]:
np.count_nonzero(arr)

9

In [73]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))